name: Deploy # 部署
 
on: # 触发条件
  push:
    branches:
      - master # 推送到 master 分支
 
  release:
    types:
      - published # 推送新版本号
 
  workflow_dispatch: # 手动触发
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout # Checkout 仓库
      uses: actions/checkout@v2
      with:
        ref: master
 
    - name: Setup Node # 安装 Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
 
    - name: Install Hexo # 安装 Hexo
      run: |
        npm install hexo-cli -g
        
    - name: Cache Modules # 缓存 Node 插件
      uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
 
    - name: Install Dependencies # 如果没有缓存或 插件有更新，则安装插件
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: | # 如果仓库里没有 package-lock.json，上传一下，npm ci 必须要有 package-lock.json
        npm ci
    - name: Generate # 生成
      run: |
        hexo clean
        hexo generate
    - name: Deploy # 部署
      run: |
        git config --global user.name "LL"
        git config --global user.email "1724647576@qq.com"
        export TZ='Asia/Shanghai'
        cd public/
        git init
        git add -A
        git commit -m "Create by workflows"
        git remote add origin [https://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@github.com/linli1724647576/Hexo]
        git push origin master -f
